= Handling Driver Errors
:type: quiz
:order: 6
:branch: 04-handling-constraint-errors

When executing a Cypher statement, certain exceptions and error cases may arise.

One error could be a _transient_ error that may be resolved if retried, for example a problem connecting to the database instance.

Another type of error could be something more permanent, for example a Syntax Error or a Constraint Error.

In the Neo4j .NET Driver, exceptions of type link:https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/exceptions/Neo4jException.html[`Neo4jException`^] will be thrown by methods that run into failure conditions.

The `Neo4jException` class extends the native Java `RuntimeException`, and as such contains a `message` property that contains detailed information about the error that has occurred.

== Error Codes

The `Neo4jException` also includes a `code()` method, which provides higher-level information about the query.

Each status code follows the same format, and includes four parts:

[source,role=nocopy]
----
Neo.[Classification].[Category].[Title]
(1)        (2)          (3)       (4)
----

1. Every Neo4j Error code is prefixed with `Neo`.
2. The Classification provides a high-level classification of the error - for example, a client-side error or an error with the database.
3. The Category provides a higher-level category for the error - for example, a problem with clustering, a procedure or the database schema.
4. The Title provides specific information about the error that has occurred.


// === Classification

// There are four classifications of error:

// [cols="1,3,1"]
// |====
// | Classification | Description | Effect on transaction

// | ClientError
// | The Client sent a bad request - changing the request might yield a successful outcome.
// | Rollback

// | ClientNotification
// | There are notifications about the request sent by the client.
// | None

// | TransientError
// | The database cannot service the request right now, retrying later might yield a successful outcome.
// | Rollback

// | DatabaseError
// | The database failed to service the request.
// | Rollback
// |====


=== Example Error Codes

Here are some common error codes that you may experience:

* `Neo.ClientError.Procedure.ProcedureCallFailed` - Failed to invoke a procedure. See the detailed error description for exact cause.
* `Neo.ClientError.Schema.ConstraintViolation` - Added or changed index entry would violate constraint.
* `Neo.ClientError.Security.Forbidden` - An attempt was made to perform an unauthorized action.
* `Neo.ClientError.Security.Unauthorized` - The client is unauthorized due to authentication failure.
* `Neo.ClientError.Statement.ParameterMissing` - The statement refers to a parameter that was not provided in the request.
* `Neo.ClientError.Statement.SyntaxError` - The statement contains invalid or unsupported syntax.
* `Neo.TransientError.General.TransactionMemoryLimit` - There is not enough memory to perform the current task.


For a comprehensive list of status codes, see link:https://neo4j.com/docs/status-codes/current/[Status Codes in the Neo4j Documentation^].

//MH: Do we need a custom error-catcher? Or just use a RuntimeException with custom message?
== Catching Errors

Below is an example of how to catch an error thrown by the Driver. It is best practice to use `try` and `catch` blocks to catch any errors that are expected and handle unexpected errors at the service or routing level.

Here is an example of how a constraint violation error, could be handled in the auth service.

.Example
[source,c#,subs="attributes+",indent=0]
----
include::{repository-raw}/main/Examples/Neo4jExamples/Exceptions.cs[tag=constraint-error]
----


== Check Your Understanding

include::./questions/1-error-code.adoc[leveloffset=+1]

include::./questions/2-error-details.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this lesson, you have learned how to interpret the errors thrown by the Neo4j .NET Driver.

In the next Challenge, you will add a unique constraint to the database and add a `try`/`catch` block the `RegisterAsync()` method to handle the error thrown when the email address is already taken.
